CREATE TYPE "public"."cliente_tipo" AS ENUM('pessoa_fisica', 'pessoa_juridica');--> statement-breakpoint
CREATE TABLE "clientes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nome" text NOT NULL,
	"tipo" "cliente_tipo" DEFAULT 'pessoa_fisica' NOT NULL,
	"cpf_cnpj" text NOT NULL,
	"rg" text,
	"orgao_emissor" text,
	"data_emissao_rg" date,
	"data_nascimento" date,
	"nacionalidade" text,
	"naturalidade" text,
	"email" text,
	"telefone" text,
	"celular" text,
	"cep" text,
	"rua" text,
	"numero" text,
	"complemento" text,
	"bairro" text,
	"cidade" text,
	"uf" text,
	"despachante" text,
	"indicado_por" text,
	"observacoes" text,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "clientes_cpf_cnpj_unique" UNIQUE("cpf_cnpj")
);
