CREATE TYPE "public"."obra_sim_nao" AS ENUM('sim', 'nao');--> statement-breakpoint
CREATE TABLE "obras" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cliente_id" uuid NOT NULL,
	"id_obra" text,
	"titulo" text,
	"tipo_obra" text,
	"item_obra_codigo" text,
	"descricao_obra" text,
	"normam_de_uso" text,
	"cp_dl_ag" text,
	"resp_tecnico" text,
	"n_crea" text,
	"rio_localizado" text,
	"distancia_rio_km" numeric,
	"area_navegacao" text,
	"atividade" text,
	"ponto_a" text,
	"ponto_b" text,
	"ponto_c" text,
	"ponto_d" text,
	"comprimento" numeric,
	"largura" numeric,
	"area_construida" numeric,
	"apoiado_sobre" text,
	"estrutura_cober" text,
	"mat_estrutura" text,
	"mat_paredes" text,
	"mat_piso" text,
	"mat_cobertura" text,
	"lista_mat_construcao_dimensoes" text,
	"font_energia" text,
	"banheiro_sn" "obra_sim_nao",
	"pia_ou_outros" text,
	"calado_car" numeric,
	"calado_leve" numeric,
	"desl_car" numeric,
	"desl_leve" numeric,
	"peso_adicional" numeric,
	"carga_suportada" numeric,
	"lotacao_max" integer,
	"coletes" integer,
	"boias" integer,
	"mat_tambores" text,
	"qnt_tambores" integer,
	"volume_tambores" numeric,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "obras" ADD CONSTRAINT "obras_cliente_id_clientes_id_fk" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE restrict ON UPDATE no action;